/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouterHistory } from "@stencil/router";
export namespace Components {
    interface AppNavigation {
        "history": RouterHistory;
    }
    interface AppRoot {
        "history": RouterHistory;
    }
    interface PageDetails {
    }
    interface PageHome {
        "history": RouterHistory;
    }
    interface PageList {
    }
    interface PageNotFound {
    }
}
declare global {
    interface HTMLAppNavigationElement extends Components.AppNavigation, HTMLStencilElement {
    }
    var HTMLAppNavigationElement: {
        prototype: HTMLAppNavigationElement;
        new (): HTMLAppNavigationElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageDetailsElement extends Components.PageDetails, HTMLStencilElement {
    }
    var HTMLPageDetailsElement: {
        prototype: HTMLPageDetailsElement;
        new (): HTMLPageDetailsElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageListElement extends Components.PageList, HTMLStencilElement {
    }
    var HTMLPageListElement: {
        prototype: HTMLPageListElement;
        new (): HTMLPageListElement;
    };
    interface HTMLPageNotFoundElement extends Components.PageNotFound, HTMLStencilElement {
    }
    var HTMLPageNotFoundElement: {
        prototype: HTMLPageNotFoundElement;
        new (): HTMLPageNotFoundElement;
    };
    interface HTMLElementTagNameMap {
        "app-navigation": HTMLAppNavigationElement;
        "app-root": HTMLAppRootElement;
        "page-details": HTMLPageDetailsElement;
        "page-home": HTMLPageHomeElement;
        "page-list": HTMLPageListElement;
        "page-not-found": HTMLPageNotFoundElement;
    }
}
declare namespace LocalJSX {
    interface AppNavigation {
        "history"?: RouterHistory;
    }
    interface AppRoot {
        "history"?: RouterHistory;
    }
    interface PageDetails {
    }
    interface PageHome {
        "history"?: RouterHistory;
    }
    interface PageList {
    }
    interface PageNotFound {
    }
    interface IntrinsicElements {
        "app-navigation": AppNavigation;
        "app-root": AppRoot;
        "page-details": PageDetails;
        "page-home": PageHome;
        "page-list": PageList;
        "page-not-found": PageNotFound;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-navigation": LocalJSX.AppNavigation & JSXBase.HTMLAttributes<HTMLAppNavigationElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-details": LocalJSX.PageDetails & JSXBase.HTMLAttributes<HTMLPageDetailsElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-list": LocalJSX.PageList & JSXBase.HTMLAttributes<HTMLPageListElement>;
            "page-not-found": LocalJSX.PageNotFound & JSXBase.HTMLAttributes<HTMLPageNotFoundElement>;
        }
    }
}
